### ISSUE TITLE
Protected packages update to version `undefined`, breaking update

### ISSUE THREAD

**Issue by HansCronau** [lropero/upgradeps#4]
Can be reproduced by adding a protected package and running upgradeps.

Example: `@fortawesome/pro-solid-svg-icons`

Upgradeps will attempt

`@fortawesome/pro-solid-svg-icons √ 5.6.3 → undefined`

resulting in

`npm ERR! Invalid tag name "^undefined"`

**Comment by lropero** [comment]
This is happening because `@fortawesome/pro-solid-svg-icons` doesn't exists (seems to me it existed at one point and the author deleted the repo).

Still, I will add a check in next version to avoid the undefined string in `package.json`.

**Comment by lropero** [comment]
This is now fixed (v1.2.0).

**Comment by HansCronau** [comment]
My bad. I assumed the package still existed because `npm outdated` showed that there was a newer version (version number and all).
